#!/usr/bin/env python3
"""
Universal TPU Test Launcher.

Runs a test executable (.npz) generated by a program definition script.
The executable must contain:
  - 'instructions': The compiled instruction stream
  - 'inputs': Dictionary of {alloc_name: numpy_array}
  - 'outputs': Dictionary of {alloc_name: expected_numpy_array}
  - 'memory_map': JSON string of memory layout

Usage:
  python3 test_launcher.py binaries/comprehensive.npz
"""

import argparse
import sys
import json
import numpy as np
from pathlib import Path

# Add project root to path for imports if running from subdir
# Path(__file__) is workflow/tools/test_launcher.py
# .parent is workflow/tools/
# .parent.parent is workflow/
# .parent.parent.parent is project root
project_root = str(Path(__file__).parent.parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from runtime.pynq_host import TpuDriver
from compiler.executable import TPUExecutable

def run_test(executable_path, bitstream=None):
    print(f"Loading test executable: {executable_path}")
    try:
        exe = TPUExecutable.load(executable_path)
        instructions = exe.instructions
        memory_map = exe.memory_map
        inputs = exe.inputs
        outputs = exe.outputs
    except Exception as e:
        print(f"Failed to load executable: {e}")
        return False

    # Initialize TPU
    try:
        # TpuDriver checks environment for overlay, or uses fallback
        tpu = TpuDriver(bitstream=bitstream)
    except Exception as e:
        print(f"Failed to initialize TPU Driver: {e}")
        return False

    print(f"  Instructions: {len(instructions)}")
    print(f"  Inputs: {list(inputs.keys())}")
    
    # 1. Write Instructions
    tpu.write_instructions(instructions)

    # 2. Write Inputs to BRAM
    print("\nWriting inputs to BRAM...")
    for name, array_data in inputs.items():
        if name not in memory_map:
            print(f"  Warning: Input '{name}' not found in memory map, skipping.")
            continue
        
        addr = memory_map[name]['addr']
        # Flatten data for writing, but keep type info
        flat_data = array_data.flatten().astype(np.float32)
        print(f"  {name:<10} -> addr {addr:<5} (shape {array_data.shape})")
        tpu.write_bram(addr, flat_data)

    # 3. Compute
    print("\nComputing...")
    tpu.compute()

    # 4. Verify Outputs
    print("\nVerifying outputs...")
    all_pass = True
    
    for name, expected in outputs.items():
        if name not in memory_map:
            print(f"  Warning: Output '{name}' not found in memory map, skipping verification.")
            continue
            
        addr = memory_map[name]['addr']
        count = expected.size
        
        # Read from BRAM
        actual = tpu.read_bram(addr, count)
        
        # Reshape for comparison if necessary
        if expected.ndim > 1:
            try:
                actual = actual.reshape(expected.shape)
            except ValueError:
                 print(f"  Error reshaping readback for {name}")
                 all_pass = False
                 continue
        
        # Compare
        # Using relatively loose tolerance for potentially accumulating float errors in hardware
        if np.allclose(actual, expected, rtol=1e-3, atol=1e-3):
            print(f"  {name:<15}: PASS")
        else:
            diff = np.abs(actual - expected)
            max_diff = np.max(diff)
            print(f"  {name:<15}: FAIL (Max diff: {max_diff:.6f})")
            all_pass = False

    return all_pass

def main():
    parser = argparse.ArgumentParser(description="Run Mini-TPU tests from .npz executables")
    parser.add_argument("executable", help="Path to test executable (.npz)")
    parser.add_argument("--bitstream", help="Path to bitstream (optional)", default=None)
    args = parser.parse_args()

    exe_path = Path(args.executable)
    if not exe_path.exists():
        print(f"File not found: {exe_path}")
        sys.exit(1)
        
    success = run_test(exe_path, args.bitstream)
    
    if success:
        print("\nResult: SUCCESS")
        sys.exit(0)
    else:
        print("\nResult: FAILURE")
        sys.exit(1)

if __name__ == "__main__":
    main()
